name: CI # name of the workflow

on:
    push: # the workflow will run when code is pushed to master branch.
        branches: [ master ]
    pull_request: # the workflow will run when a pull request is created/ updated for the master branch.
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        -   name: Checkout code
            uses: actions/checkout@v4
            
        -   name: Set up JDK 21
            uses: actions/setup-java@v4
            with:
                distribution: 'adopt'
                java-version: '21'
                
        -   name: Build with Gradle
            run: gradle build
            
        -   name: Upload Build Artifacts
            uses: actions/upload-artifact@v4
            with:
                name: build-artifacts
                path: build/libs/**
       
        -   name: Run Unit Test
            run: gradle test
            
        -   name: Upload Test Reports
            uses: actions/upload-artifact@v4
            with:
                name: test-reports
                path: build/reports/tests/** # upload all the files in this path
        
        -   name: Generate code coverage report
            run: gradle jacocoTestReport
        
        -   name: Upload code coverage report
            uses: actions/upload-artifact@v4
            with:
                name: code-coverage-report
                path: build/reports/jacoco/test/html/**
        
        -   name: Run Deployment
            run: java -jar build/libs/hello-world-java-V1.jar
